"""Hold the config schema, the web read model and the hand-written form together.

The config page is not generated from ``src.config_schema``; ``config.html``
and ``dashboard.js`` name each field by hand. That is how the drift in #307 /
#308 went unnoticed: ``/api/config/schema`` reported two secrets as never set
because their ``_*_set`` flags were named after something else, the quotes
path was rendered but never collected, and several documented options had no
``FieldSpec`` at all. These tests fail on each of those shapes.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from src.config_schema import all_field_specs, secret_field_paths, to_json
from src.web.config_editor import get_config_for_web
from src.web.routes.config import _flatten_for_schema

ROOT = Path(__file__).resolve().parents[1]
HTML = (ROOT / "src/web/templates/config.html").read_text()
JS = (ROOT / "src/web/static/dashboard.js").read_text()

# Editable through POST /api/config (and so in the schema) but deliberately
# not on the form: calendar identity and CalDAV settings are credential-adjacent
# and shown read-only in the Credential Status block; the two list-shaped
# specials have their own editors (schedule table, rules textarea) that the
# data-field scan below does not see.
NOT_ON_FORM = {
    "google.calendar_id",
    "google.contacts_email",
    "google.caldav_url",
    "google.caldav_username",
    "google.caldav_calendar_url",
    "purpleair.sensor_id",
    "theme_schedule",
    "theme_rules",
}


@pytest.fixture(scope="module")
def flat_values(tmp_path_factory):
    path = tmp_path_factory.mktemp("cfg") / "config.yaml"
    path.write_text("")
    return _flatten_for_schema(get_config_for_web(str(path)))


def test_every_schema_field_has_a_value_in_the_read_model(flat_values):
    missing = [s.path for s in all_field_specs() if s.path not in flat_values]
    assert not missing, f"get_config_for_web() carries no value for: {missing}"


def test_secrets_report_has_value_from_their_own_flag(tmp_path):
    """A set secret must read has_value=True — the flag name must match the path."""
    cred = tmp_path / "sa.json"
    cred.write_text("{}")
    pw = tmp_path / "pw.txt"
    pw.write_text("x")
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        "weather:\n  api_key: k\n"
        "purpleair:\n  api_key: k\n  sensor_id: 5\n"
        f"google:\n  service_account_path: {cred}\n  ical_url: https://a/b.ics\n"
        "  additional_ical_urls: [https://c/d.ics]\n"
        f"  caldav_password_file: {pw}\n"
    )
    schema = to_json(values=_flatten_for_schema(get_config_for_web(str(cfg))))
    fields = {f["path"]: f for s in schema["sections"] for f in s["fields"]}
    unset = [p for p in secret_field_paths() if not fields[p]["has_value"]]
    assert not unset, f"secrets reported as unset: {unset}"
    # A display flag for a non-secret field must not become its value.
    assert fields["purpleair.sensor_id"]["value"] == 5


def test_every_editable_field_is_on_the_form_and_collected():
    editable = {s.path for s in all_field_specs() if s.editable and not s.secret}
    on_form = set(re.findall(r'data-field="([^"{}]+)"', HTML))
    # The cache rows are generated by a Jinja loop over (id, field, …) tuples.
    on_form |= set(re.findall(r'\("cfg-[\w-]+",\s*"([\w.]+)"', HTML))
    collected = set(re.findall(r'patch\["([\w.]+)"\]', JS))
    collected |= set(re.findall(r'\["cfg-[\w-]+",\s*"([\w.]+)"', JS))
    expected = editable - NOT_ON_FORM
    assert not expected - on_form, f"not on the form: {sorted(expected - on_form)}"
    assert not expected - collected, f"never collected: {sorted(expected - collected)}"


def test_log_level_choices_cover_every_accepted_name():
    from src.config import is_known_log_level
    from src.config_schema import LOG_LEVELS

    for name in ("DEBUG", "INFO", "WARNING", "WARN", "ERROR", "CRITICAL", "FATAL"):
        assert is_known_log_level(name)
        assert name in LOG_LEVELS
